### ISSUE TITLE
爱奇艺是不是已经失效了

### ISSUE THREAD

**Issue by xyuanmu** [jiangli373/nodeParseVideo#1]
你好！刚刚使用这个工具解析爱奇艺的视频，缩略图可以正常获取，就是视频地址无法访问，请问是不是爱奇艺的解析失效了，还是爱奇艺不能下载只能在线看？谢谢！

解析奔跑吧兄弟返回数据：
{ mp4: [ 'http://114.80.196.201/videos/v0/20150418/44/da/aaed84c2080cef8719371109ff521c04.mp4?key=05991a6c05a6c47df22af214f26dbb5a6&src=iqiyi.com&m=v&qd_src=ih5&qd_tm=1435111423088&qd_ip=104.130.247.175&qd_sc=2cdbfc4e3f620b67eda61622d7e48aef&ip=104.130.247.175&uuid=a0a8313-558a0fff-36' ],                                                                       
  title: '奔跑吧兄弟第2季之真假雅典娜 范冰冰李晨对撕',                                                                                                                                                  
  coverImg: 'http://pic7.qiyipic.com/image/20150420/88/7c/v_109086466_m_601_m2.jpg' }

**Comment by jiangli373** [comment]
你好，你上面发的这个mp4地址，在我这里是可以打开的的
![494df5a7-de3d-4b44-b8e9-884ffd923cc6](https://cloud.githubusercontent.com/assets/1632862/8321434/760476d2-1a59-11e5-97a9-15e920a1fbeb.png)

**Comment by xyuanmu** [comment]
@jiangli373 谢谢你的回复，也许是我这里网络的问题吧，看来爱奇艺下载不了了。
