### ISSUE TITLE
恕我才疏学浅，没弄明白要怎么执行test.js

### ISSUE THREAD

**Issue by LSD08KM** [jiangli373/nodeParseVideo#2]
我需要单独写一个html来调用它吗？

**Comment by jiangli373** [comment]
@LSD08KM  
因为这个库使用nodejs写的，可以通过node test.js 可以测试下能否解析出来正确的视频地址。
html无法直接调用，因为这里会调用视频网站的接口，html调用的话，会涉及到跨域的问题，你可以在自己的服务器上做一个中转

**Comment by LSD08KM** [comment]
好的，我明白了。谢谢回答
