### ISSUE TITLE
爱奇艺解析出来的m3u8地址打不开吖朋友

### ISSUE THREAD

**Issue by Menco0709** [jiangli373/nodeParseVideo#3]
就是用你的例子(http://www.iqiyi.com/v_19rrnbyreg.html)
能解析出来是http://114.80.196.201/487/4ced739873478d14f9fd68f896118f4e.m3u8
但是打不开吖

**Comment by jiangli373** [comment]
@Menco0709 爱奇艺改变了加密算法，所以暂时这个库里面关于爱奇艺的解析暂时失效了，等有时间再做研究
